# -*- coding: utf-8 -*-
"""exerc2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18k7XmeGy4H23nDifxAqs851DZ-WXyUzg
"""

#exerc_2
import random

matriz =[
    [10, 22, 33],
    [16, 31, 65],
    [6, 18, 37]
]

def excluir(linha, coluna): 
    del(matriz[linha][coluna])
    print(matriz)

linha = int(input('linha: '))
coluna = int (input('coluna: ')) 

excluir(linha, coluna);